### PR TITLE
Added Areas support. Updated example application to include areas sup…

### PR DESCRIPTION
**Pull request by sethsteenken**
…port and areas with custom routing.

Included a NodeKey class to handle the logic around building a key from the route dictionary. Updated the extension methods on type responsible for generating the node keys to include a check on the AreaAttribute. Tested logic against example app which now includes Area support.

### CODE REVIEW

**Comment by sethsteenken** [comment]
Related issues - #33 #37

**Comment by zHaytam** [comment]
Hello,
Thank you very much for the PR!
I will be trying it tomorrow to see if it's ready to be merged, sorry for the delay.

**Comment by sethsteenken** [comment]
Sure thing! No worries at all on the delay. Hit me up if you have any questions or concerns about the PR.

**Comment by zHaytam** [comment]
Looks good to me, merged!  
Thanks again, 3.5.0 will be in NuGet shortly!

**Comment by sethsteenken** [comment]
Excellent, thank you!

**Pull request merged**
