### PR TITLE
Update localizer BreadcrumbTagHelper

### PR DESCRIPTION
**Pull request by icesasoftcorp**
BreadcrumbTagHelper, you don't need to create a class with the same language resource name and you can add a different namespace.
the example was updated so that its use can be seen.

### CODE REVIEW

**Comment by zHaytam** [comment]
Hello, thanks for the PR!
May I know what problem this solves? What does specifying the assembly name do?

**Comment by icesasoftcorp** [comment]
It is a slight fix, so that you no longer have to create an unnecessary class, in the example is BreadcrumbResources.cs
Here you send it directly to the language resource which may be in another layer and may have another name space.

with this change it uses the name of the resource and the assembly that is executing it, without the need for the name space to be the same

**Comment by zHaytam** [comment]
I see that you've added some things in the csproj, I personally never used them. If someone does want to create a class and work with it (like we had previously), would this approach still work?

**Comment by icesasoftcorp** [comment]
this change does not really affect if they use it in the previous way, now they can use it in several ways

**Comment by zHaytam** [comment]
Alright, thank you again for the PR!

**Pull request merged**
