### PR TITLE
added posibility for assigning routevalues through BreadcrumbAttribute

### PR DESCRIPTION
**Pull request by oleksandrnechaiev**
Now we can add it like this
second param is the name of area if in config routes we have like this {area=Home}/{controller=Home}/{action=Index}

[DefaultBreadcrumb("Home", "Home")]
same for BreadcrumbAttribute

### CODE REVIEW

**Comment by zHaytam** [comment]
Hi and Thank you for the PR.
I don't think it's a good idea to have `RouteValues` in the attributes since you can't really set them anyways, might aswell just store the Area's name and set it in the nodes ^^

**Comment by oleksandrnechaiev** [comment]
Hi,
yeah, you are right, well, then we should replace it with Area's name and add creation of it inside constructor instead of just assigning. What do you think?

**Comment by zHaytam** [comment]
Yeah just keep the area name in the attribute and pass it on the node's ctor.
Commit the change and I will merge the pr :p

**Comment by zHaytam** [comment]
Thank you!
I will update the NuGet package when I finish icons.

**Comment by oleksandrnechaiev** [comment]
Thank you, please, let me know when you update it=)
Thanks!

**Comment by zHaytam** [comment]
Hi, sorry for the delay.
The package is now uploaded (https://www.nuget.org/packages/SmartBreadcrumbs/1.0.5).

**Comment by oleksandrnechaiev** [comment]
Thank you very much!

**Pull request merged**
